spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/finance_tracker
    username: devuser
    password: devpassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true